version: '3'

services:
  backend:
    build: .
    container_name: nayzi-backend
    restart: always
    ports:
      - '8004:8000'
    command: bash -c "export environment=docker.env && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
