# Generated by Django 3.0.6 on 2020-08-15 10:12

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='seo_title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='seo_description')),
                ('thumbnail', models.ImageField(upload_to='category_thumbnail', verbose_name='thumbnail')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'blog_category',
                'verbose_name_plural': 'blog_categories',
                'db_table': 'blog_categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='comment')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(max_length=13, verbose_name='phone')),
                ('first_name', models.CharField(max_length=255, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last_name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=255, verbose_name='status')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Comment', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='CommentedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object_id')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='comment')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content_type')),
            ],
            options={
                'verbose_name': 'commented_items',
                'verbose_name_plural': 'commented_items',
                'db_table': 'commented_items',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='seo_title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='seo_description')),
                ('content', froala_editor.fields.FroalaField()),
                ('time', models.IntegerField(verbose_name='time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnail', verbose_name='thumbnail')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('cats', models.ManyToManyField(blank=True, related_name='blog_cat', to='blog.BlogCategory', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blog',
                'db_table': 'blog',
            },
        ),
    ]
