# Generated by Django 3.0.6 on 2020-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cats',
            field=models.ManyToManyField(blank=True, related_name='blog_cat', to='blog.BlogCategory', verbose_name='categories'),
        ),
    ]
