# Generated by Django 3.0.6 on 2020-05-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
