# Generated by Django 3.0.6 on 2020-05-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegallery',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
