# Generated by Django 3.0.6 on 2020-05-08 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicegallery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegallery',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='description'),
            preserve_default=False,
        ),
    ]
