# Generated by Django 3.0.6 on 2020-05-10 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200508_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
