# Generated by Django 3.0.6 on 2020-05-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_servicegallery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
    ]
