# Generated by Django 3.0.6 on 2020-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='customer_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='file_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='file_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_registered_from_here',
            field=models.BooleanField(default=False, verbose_name='is_registered_from_here'),
        ),
    ]
