# Generated by Django 3.0.6 on 2020-05-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='user_thumbnail', verbose_name='thumbnail'),
        ),
    ]
