# Generated by Django 3.0.6 on 2020-05-20 16:07

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('thumbnail', models.ImageField(upload_to='category_thumbnail', verbose_name='thumbnail')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'doctor_category',
                'verbose_name_plural': 'doctor_categories',
                'db_table': 'doctor_categories',
            },
        ),
        migrations.CreateModel(
            name='DoctorCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'doctor_certificate',
                'verbose_name_plural': 'doctor_certificates',
                'db_table': 'doctor_certificates',
            },
        ),
        migrations.CreateModel(
            name='DoctorEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni', models.CharField(max_length=255, verbose_name='uni')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'doctor_education',
                'verbose_name_plural': 'doctor_educations',
                'db_table': 'doctor_educations',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='full_name')),
                ('job_position', models.CharField(max_length=255, unique=True, verbose_name='job_position')),
                ('about', froala_editor.fields.FroalaField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnail', verbose_name='thumbnail')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='mobile')),
                ('twitter_link', models.URLField(blank=True, max_length=512, null=True, verbose_name='twitter_link')),
                ('linkedin_link', models.URLField(blank=True, max_length=512, null=True, verbose_name='linkedin_link')),
                ('instagram_link', models.URLField(blank=True, max_length=512, null=True, verbose_name='instagram_link')),
                ('cats', models.ManyToManyField(blank=True, related_name='doctor_cat', to='doctor.DoctorCategory', verbose_name='categories')),
                ('certificates', models.ManyToManyField(blank=True, related_name='doctor_cer', to='doctor.DoctorCertificate', verbose_name='certificates')),
                ('educations', models.ManyToManyField(blank=True, related_name='doctor_edu', to='doctor.DoctorEducation', verbose_name='educations')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
                'db_table': 'doctors',
            },
        ),
    ]
