# Generated by Django 3.0.6 on 2020-05-23 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='join_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='join_at'),
            preserve_default=False,
        ),
    ]
