# Generated by Django 3.0.6 on 2020-05-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200523_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='job_position',
            field=models.CharField(max_length=255, verbose_name='job_position'),
        ),
    ]
