# Generated by Django 3.0.6 on 2020-07-10 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20200607_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='order',
            field=models.SmallIntegerField(default=0, unique=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
